### ISSUE TITLE
ENHANCEMENT: Make the Reed Solomon error count visible

### ISSUE THREAD

**Issue by n2cr** [opensatelliteproject/OpenSatelliteProject#10]
Based upon a suggestion in #HearSat, make the Reed Solomon error count visible in the goesdump GUI and web page.

**Comment by racerxdl** [comment]
But they're visible, there are four RS Frames per Satellite Frame, its just over the Sync Word.
![image](https://cloud.githubusercontent.com/assets/578310/24076819/70e9498a-0c19-11e7-84fa-15272ae96c11.png)

**Comment by n2cr** [comment]
Concur.  Issue closed.
