### ISSUE TITLE
Should all of these programs work with GOES-17 now that it is online?..

### ISSUE THREAD

**Issue by BLB5000** [opensatelliteproject/OpenSatelliteProject#17]
I am currently try to receive images from GOES-17 so I am wondering if it will work with your programs? It's just that it is was not listed in the description.

**Comment by racerxdl** [comment]
Yes @BLB5000 works with the new generation. GOES 16 , 17 and 18 all have the same protocol / modulation.

**Comment by BLB5000** [comment]
Thank you very much Lucas! Your advice is so hugely appreciated. I hope you
have a great day.
