### ISSUE TITLE
ENHANCEMENT: Add a value to the goesdump configuration file which specifies the syslog facility

### ISSUE THREAD

**Issue by n2cr** [opensatelliteproject/OpenSatelliteProject#9]
Allow the user to specify which syslog facility[https://en.wikipedia.org/wiki/Syslog#Facility](url) to which the syslog messages will be sent.  This will allow all OpenSatelliteProject messages to be put in a single file via the use of LOG_LOCALx facility values.

**Comment by racerxdl** [comment]
Done by @n2cr !
